### ISSUE TITLE
使用指令以后报错

### ISSUE THREAD

**Issue by Cherryluoying** [Nekoer/mirai-plugins-novelai#3]
mirai版本：2.12.3
log:
`2022-12-21 13:37:41 E/novelai: Exception in coroutine Plugin com.hcyacg.novelai of novelai
java.lang.IllegalArgumentException: Unsupported image type (mirai) for ExternalResource net.mamoe.mirai.internal.utils.ExternalResourceImplByByteArray@6631a8c0, considering use gif/png/bmp/jpg format. image header: 7B 22 64 65 74 61 69 6C 22 3A 22 4E 6F 74 20 46 6F 75 6E 64 22 7D
        at net.mamoe.mirai.internal.message.image.ImageDecoderKt.calculateImageInfo(ImageDecoder.kt:160)
        at net.mamoe.mirai.internal.contact.GroupImpl$uploadImage$lambda-15$$inlined$runBIO$1.invoke(CoroutineUtils.kt:194)
        at kotlinx.coroutines.InterruptibleKt.runInterruptibleInExpectedContext(Interruptible.kt:51)
        at kotlinx.coroutines.InterruptibleKt.access$runInterruptibleInExpectedContext(Interruptible.kt:1)
        at kotlinx.coroutines.InterruptibleKt$runInterruptible$2.invokeSuspend(Interruptible.kt:43)
        at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:33)
        at kotlinx.coroutines.DispatchedTask.run(DispatchedTask.kt:106)
        at kotlinx.coroutines.internal.LimitedDispatcher.run(LimitedDispatcher.kt:42)
        at kotlinx.coroutines.scheduling.TaskImpl.run(Tasks.kt:95)
        at kotlinx.coroutines.scheduling.CoroutineScheduler.runSafely(CoroutineScheduler.kt:570)
        at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.executeTask(CoroutineScheduler.kt:749)
        at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.runWorker(CoroutineScheduler.kt:677)
        at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.run(CoroutineScheduler.kt:664)`

**Comment by cafrew** [comment]
我也遇到了，已经按照commit hash换成对应的webui版本了

**Comment by KevinYamazaki** [comment]
> 我也遇到了，已经按照commit hash换成对应的webui版本了
大佬您好，请问下启动该仓库后，应该如何配置config参数呢？ 我看到参数中有用户名 密码 管理员，。它们对应的是什么账户？ 谢谢！
